dbms.security.allow_csv_import_from_file_urls=false
dbms.security.procedures.allowlist=apoc.convert.*,apoc.text.*
dbms.security.procedures.unrestricted=apoc.convert.*,apoc.text.*
internal.dbms.cypher_ip_blocklist=0.0.0.0/0,::/0
