name: Test Suite
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Run unit tests
        run: |
          make test_unit
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn install
      - uses: pre-commit/action@v2.0.2
        with:
          extra_args: --all-files --show-diff-on-failure
          token: ${{ secrets.GITHUB_TOKEN }}
